/**
 * Cloud & Infrastructure as Code (Terraform) Simulator (Chapter 5.1.4 & Chapter 7.3)
 * Simulates Terraform state and AWS resource lifecycle.
 */

let provisionedResources = [
  { id: "i-09ab12cd34ef5678", type: "aws_instance", name: "devops-worker-node-1", size: "t3.xlarge", region: "ap-southeast-1", status: "running", cost: "$0.166/hr" },
  { id: "s3-horizon-artifacts-bucket", type: "aws_s3_bucket", name: "devops-ci-artifacts-store", size: "128 GB", region: "ap-southeast-1", status: "active", cost: "$0.023/GB" },
  { id: "rds-postgres-primary", type: "aws_db_instance", name: "production-postgres-v16", size: "db.r6g.large", region: "ap-southeast-1", status: "available", cost: "$0.24/hr" }
];

export class CloudService {
  static getResources() {
    return provisionedResources;
  }

  static generateTerraform(resourceType, params = {}) {
    if (resourceType === "aws_instance" || resourceType === "ec2") {
      return `terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "ap-southeast-1"
}

resource "aws_instance" "smart_devops_node" {
  ami           = "ami-0c55b159cbfafe1f0" # Ubuntu 24.04 LTS
  instance_type = "${params.instanceType || "t3.medium"}"
  key_name      = "devops-deployer-key"

  tags = {
    Name        = "${params.name || "smart-devops-worker"}"
    Environment = "production"
    ManagedBy   = "Agentic-DevOps-Assistant"
  }

  root_block_device {
    volume_size           = 50
    volume_type           = "gp3"
    delete_on_termination = true
  }
}`;
    }

    return `# Terraform Configuration generated by Smart DevOps Assistant
resource "aws_s3_bucket" "pipeline_storage" {
  bucket = "devops-pipeline-storage-${Date.now()}"
  acl    = "private"
}`;
  }

  static async applyTerraform(resourceName, resourceType = "aws_instance") {
    const newRes = {
      id: `i-${Math.random().toString(16).substring(2, 10)}`,
      type: resourceType,
      name: resourceName || `worker-${Date.now().toString().slice(-4)}`,
      size: "t3.medium",
      region: "ap-southeast-1",
      status: "running",
      cost: "$0.0416/hr"
    };

    provisionedResources.push(newRes);
    return {
      success: true,
      resource: newRes,
      terraformOutput: `Apply complete! Resources: 1 added, 0 changed, 0 destroyed.\nOutputs:\ninstance_id = "${newRes.id}"\npublic_ip = "54.254.120.${Math.floor(Math.random() * 200 + 10)}"`
    };
  }
}
